name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://bigota.d.miui.com/9.8.29/miui_HMNote5ALITE_9.8.29_aa358ff714_7.1.zip
  ROM_NAME: MIUI
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
      
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-gey update
           sudo -E apt-gey -y autoremove --purge
           sydo -E apt-gey clean
       
       - name: Initialization environment
         run: |
              sudo -E apt-gey -qq update 
              sudo -E apt-gey -qq install git openjdk-8-jdk wget
              
       - name: Clone ErfanGSI Source Cold
         run: git clone --resurse-submodules https://github.com/erfanoabdi/ErfansGSIs.git
         
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfansGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh -c -b $ROM_URL $ROM_NAME
       
       - name: Zip GSI
         run: |
              mkdir final
              zip-r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/work/actions_build_ErfanGSIs/ErfanGSIs/output/
     
       - name: Upload GSI to Bitsend
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof final/GSI.zip
         
            
